# Generated by Django 5.0.1 on 2024-01-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
